Fix taplog
Summary:
Taplog broke at some point and was failing with this error:
```
(lldb) taplog
error: could not get num args: can't find callable: sys.modules['FBFindCommands'].FBTapLoggerCommand.taplog_callback
```

It looks like `SetScriptCallbackFunction()` is the canonical API for providing a callback. I hoisted the function to the module so we can independently import it for visibility in LLDB.

Reviewed By: adamjernst

Differential Revision: D25681511

fbshipit-source-id: c95378c877f77e6faf201c55a4bfa8573ba84a13